name: github pages (main)

on:
  push:
    branches:
      - main  # Set a branch to deploy
          
jobs:
  branchcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: sudo snap install remarshal && sudo snap install jq && sudo snap install yq
      - name: Check & fix branch if necessary
        run: |
          config=$(yaml2json static/admin/config.yml)
          branch=$(echo "$config" | jq -r '.backend.branch') && echo "$branch"
          if ! [ "$branch" == "main" ]; then yq -i e '.backend.branch = "main"' static/admin/config.yml && echo "> modified static/admin/config.yml file:" && cat static/admin/config.yml; fi
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: If changes have been made, commit and push
        run: if [ -n "$(git status --porcelain)" ]; then git add -A && git commit -m "Fixed netlifycms branch" && git push; else echo "No changes"; fi
  deploy:
    runs-on: ubuntu-18.04
    needs: [ branchcheck ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: stefanzweifel/git-auto-commit-action@v4
      - run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
